
import prisma from "@/lib/prisma";
import PortfolioGrid from "./PortfolioGrid";

export const dynamic = 'force-dynamic'; // Ensure we always get fresh data

export default async function ShowcasePage() {
    const projects = await prisma.repository.findMany({
        where: {
            // Only show projects that have at least a description or analysis
            description: { not: null }
        },
        select: {
            id: true,
            name: true,
            description: true,
            url: true,
            previewImageUrl: true,
            technologies: {
                select: { name: true }
            },
            businessCanvas: {
                select: {
                    valueProposition: true,
                    customerSegments: true,
                    revenueStreams: true
                }
            }
        },
        orderBy: {
            updatedAt: 'desc'
        }
    });

    // Transform data for the Client Component
    const formattedProjects = projects.map(p => ({
        ...p,
        description: p.description || "No description available.",
        technologies: p.technologies.map(t => t.name),
        businessCanvas: p.businessCanvas ? {
            valueProposition: parseJsonSafe(p.businessCanvas.valueProposition),
            customerSegments: parseJsonSafe(p.businessCanvas.customerSegments),
            revenueStreams: parseJsonSafe(p.businessCanvas.revenueStreams),
        } : null
    }));

    return (
        <div className="min-h-screen bg-slate-950 text-slate-100 font-sans selection:bg-purple-500/30">

            {/* Hero Section */}
            <section className="relative pt-32 pb-20 px-6 overflow-hidden">
                {/* Abstract Background Elem */}
                <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[1000px] h-[500px] bg-purple-900/20 rounded-full blur-3xl opacity-30 pointer-events-none" />

                <div className="max-w-7xl mx-auto text-center relative z-10">
                    <div className="inline-block mb-4 px-4 py-1.5 rounded-full border border-purple-500/30 bg-purple-500/10 text-purple-300 text-sm font-medium tracking-wide">
                        AVAILABLE FOR HIRE
                    </div>
                    <h1 className="text-5xl md:text-7xl font-bold mb-6 bg-clip-text text-transparent bg-gradient-to-b from-white via-slate-200 to-slate-500 tracking-tight">
                        Steffen Quievreux
                    </h1>
                    <p className="text-xl md:text-2xl text-slate-400 max-w-2xl mx-auto leading-relaxed">
                        Scalable Solution Architect & Product Engineer. <br />
                        Transforming <span className="text-white font-medium">70+ codebases</span> into sustainable business value.
                    </p>
                </div>
            </section>

            {/* Main Content */}
            <main className="max-w-7xl mx-auto px-6 pb-32">
                <div className="flex justify-between items-center mb-12 border-b border-slate-800/50 pb-6">
                    <div>
                        <h2 className="text-2xl font-semibold text-white">Product Portfolio</h2>
                        <p className="text-slate-500 mt-1">Explore the intelligence behind the code.</p>
                    </div>
                    <div className="text-right hidden sm:block">
                        <div className="text-3xl font-bold text-white">{projects.length}</div>
                        <div className="text-xs text-slate-500 uppercase tracking-widest">Active Projects</div>
                    </div>
                </div>

                <PortfolioGrid projects={formattedProjects} />
            </main>

            {/* Simple Footer */}
            <footer className="border-t border-slate-900 bg-slate-950 py-12 text-center text-slate-600 text-sm">
                <p>&copy; {new Date().getFullYear()} Steffen Quievreux. Generated by Vibecoder Intelligence.</p>
            </footer>
        </div>
    );
}

function parseJsonSafe(val: any): any[] {
    if (!val) return [];
    if (Array.isArray(val)) return val;
    try {
        return JSON.parse(val);
    } catch {
        return [];
    }
}
