import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "VibeCoder Architect Reviewer",
  description: "Generated by create next app",
};

import VersionDisplay from "./components/VersionDisplay";
import SessionProvider from "./components/SessionProvider";
import ThemeProvider from "./components/ThemeProvider";
import GlobalSearch from "./components/GlobalSearch";

// ... (imports)

import Navbar from "./components/Navbar";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-50 dark:bg-slate-950`}
        suppressHydrationWarning
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SessionProvider>
            <GlobalSearch />
            <Navbar />
            <main className="min-h-screen">
              {children}
            </main>
            <VersionDisplay />
          </SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
