#!/bin/bash
# Batch script to upgrade repositories to Tailwind CSS v4.0

REPOS=(
  "playlist_generator"
  "media-project-manager"
  "kitools"
  "comicgenerator-techeroes"
  "Google-Visual-Story-Generator-"
  "Artheria-Healing-Visualizer"
  "screenshotgallerysystem"
  "birdie-flight-revamp"
  "inspect-whisper"
  "techeroes-quiz"
  "VoiceStage"
  "bit-blast-studio"
  "art-vibe-gen"
  "sound-bowl-echoes"
  "broetchen-wochenende-bestellung"
  "visual-flyer-snap"
  "ai-portfolio-fly-website"
  "albumpromotion"
  "agent-dialogue-manager"
  "inspect-sync-scribe"
  "melody-maker"
  "clip-sync-collab"
  "youtube-landing-page"
  "DreamEdit"
  "OsteoConnect"
  "Audio-Transkriptor"
  "visualimagecomposer"
  "audio-mastering"
  "ballermanni-video-generator"
  "colab-monk-generator"
  "comicgenerator"
  "drawio-mcp-vercel"
  "epdfframework"
  "Essensbestellung"
  "hashimoto"
  "hugofirebase"
  "leadmagnet-question"
  "leadmagnet-quiz-mitochondrien"
  "loopcraft"
  "network-architect"
  "numerorologie"
  "runninggame"
  "s3-mcp-server"
  "shader"
  "simplehosting"
  "sonic-pi-chat-gpt"
  "Speechering"
  "steffenquievreux"
  "svg-grafik-generator"
  "veridex"
  "vibesdk-production"
  "Videoedidshare"
  "visual-image-composer"
  "vr-fingers"
  "Waldessenz"
  "ACID-MONK-GENERATOR"
  "noobgallery"
)

echo "🚀 Starting Tailwind v4 Upgrade for ${#REPOS[@]} repositories..."
echo "---"

for repo in "${REPOS[@]}"; do
  echo ""
  echo "📦 Processing $repo..."
  node scripts/upgrade-tailwind-v4.js "$repo"
  
  if [ $? -eq 0 ]; then
    echo "✅ $repo complete"
  else
    echo "❌ $repo failed"
  fi
  echo "---"
done

echo ""
echo "🎉 Tailwind v4 Upgrade complete!"
echo "Check the PRs on GitHub for each repository."
